### ISSUE TITLE
Only lists secret keys when creating Kubernetes secret resources.

### ISSUE THREAD

**Issue by goodsky** [Hexadite/acs-keyvault-agent#12]
The README indicates that all secret values should be enumerated if the SECRETS_KEYS variable is not present. This is only true for the case where secrets are stored as Kubernetes secrets objects.

I have a branch forked where I've added this functionality: [https://github.com/GoodSky/acs-keyvault-agent/commit/fa8eadc160befdbba2bd6c6eadb879cdd1593ac0](https://github.com/GoodSky/acs-keyvault-agent/commit/fa8eadc160befdbba2bd6c6eadb879cdd1593ac0)

**Comment by idanlevin** [comment]
@GoodSky thanks! can you open a PR?
