### ISSUE TITLE
Use image with MSI on AKS

### ISSUE THREAD

**Issue by toorog** [Hexadite/acs-keyvault-agent#14]
We have used this image to get certificates for our webserver from keyVault. As there is now the possibility to use MSI on AKS, I wonder how to use the managed identity instead of utilizing the serviceprincipal to authenticate to keyvault.

Is there anything planned to support this scenario?

I assume you wouln't have to change anything as MSI is transparent from application perspective.

**Comment by idanlevin** [comment]
This is already supported, check out the examples folder

**Comment by toorog** [comment]
Thanks. Didn't have a look in there. Just checked the readme and tried this on my own.
