### ISSUE TITLE
Typo in variable name

### ISSUE THREAD

**Issue by anand-raju** [Hexadite/acs-keyvault-agent#17]
The required environment variable for the program has “SERVICE_PRINCIPLE_FILE_PATH”. It should be “SERVICE_PRINCIPAL_FILE_PATH”.

**Comment by stvhwrd** [comment]
This would take equal time to fix as it does to report, @anand-raju. Pointing out the error is helpful, but submitting a PR for the fix is much better -- please consider doing so.

**Comment by idanlevin** [comment]
outdated
