### ISSUE TITLE
Create Kubernetes One Secret which has more than one  key value getting Azure Vault Secret

### ISSUE THREAD

**Issue by emre141** [Hexadite/acs-keyvault-agent#31]
Hi,
The current version of repo  is able to supply create one kubernetes secret that has more than key value and key differ from default "secret"  as below
``root@cloudyanke:/opt/certificates/rabbitmqazurerc# kubectl describe secret mqttservice-rabbitmq-ha``

Name:         mqttservice-rabbitmq-ha
Namespace:    conn
Labels:       app=rabbitmq-ha
              chart=rabbitmq-ha-1.0.0
              heritage=Helm
              release=mqttservice
Annotations:  <none>

Type:  Opaque

Data
rabbitmq-password:             8 bytes
rabbitmq-username:             8 bytes
definitions.json:              1525 bytes
rabbitmq-erlang-cookie:        32 bytes
rabbitmq-management-password:  24 bytes
rabbitmq-management-username:  10 bytes

**Comment by idanlevin** [comment]
Hi, it's unclear what this is issue is about? is this a bug? feature request? 

Either way, contributions are welcome!

**Comment by emre141** [comment]
Hi,
Yes You right it I mean is not bug might be feature request. Currently Is it support one key and value that have taken from Azure Key Vault Secret  to create one  kubernetes secret ?

**Comment by idanlevin** [comment]
outdated, pls reopen if still relevant
