### ISSUE TITLE
Support for keyvault cert already in PEM format

### ISSUE THREAD

**Issue by alexhcheng** [Hexadite/acs-keyvault-agent#33]
Tthe keyvault agent fails if the cert in keyvault is already created in PEM format. 

|2020-06-18 17:51:09,774|INFO |1|139744735868672|keyvault-agent|Secret is backing certificate. Dumping private key and certificate.
|2020-06-18 17:51:09,774|ERROR|1|139744735868672|keyvault-agent|Secret is not in pkcs12 format

**Comment by alexhcheng** [comment]
@idanlevin , please take a look

**Comment by idanlevin** [comment]
outdated, closing, please re-open if still relevant
