### ISSUE TITLE
Python 2 is no longer supported by the Python core team.

### ISSUE THREAD

**Issue by SwatantraYadav** [Hexadite/acs-keyvault-agent#48]
Is there a fix for this error?

/usr/local/lib/python2.7/dist-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
from cryptography.hazmat.primitives.asymmetric.utils import (
|2022-03-08 22:08:11,297|INFO |1|127115567826752|keyvault-agent|Grabbing secrets from Key Vault
|2022-03-08 22:08:11,297|INFO |1|127115567826752|keyvault-agent|Parsing Service Principle file from: /etc/kubernetes/azure.json
|2022-03-08 22:08:11,298|INFO |1|127115567826752|keyvault-agent|AAD tenant auto detection turned off. Using tenant id <scrubbed> from cloud config
|2022-03-08 22:08:11,298|INFO |1|127115567826752|keyvault-agent|Parsing Service Principle file completed
|2022-03-08 22:08:11,299|INFO |1|127115567826752|keyvault-agent|Using MSI

**Comment by idanlevin** [comment]
@SwatantraYadav is this still happening with the latest Dockerfile which is already Python 3? 

This PR should have already fixed it - 
https://github.com/Hexadite/acs-keyvault-agent/pull/39/files

**Comment by SwatantraYadav** [comment]
Hello Idan,

I built my image using a different dockerfile that I am attaching.

Can you please verify if that is correct or should I use the one in the master branch. Also can you please let me know what this user is:

RUN useradd -m -u 999 appuser

In my docker file should i change that to something else?

Thank you and regards,
Swatantra
________________________________

**Comment by idanlevin** [comment]
hi, I'm closing this issue.

The error you received is related to the Dockerfile you used, you're more than welcome to use the Dockerfile in the master branch or simply change yours to use the right version of Python 3.

The "useradd" line simply adds a non-root user for better security, this way the init container doesn't run as root.

**Comment by SwatantraYadav** [comment]
@hexadite-idan When I use the docker file from the master branch i get the following error:
-----------------------------------------------------------------------------
|2022-03-11 06:10:17,323|INFO |1|126224785700672|keyvault-agent|Grabbing secrets from Key Vault
|2022-03-11 06:10:17,323|INFO |1|126224785700672|keyvault-agent|Parsing Service Principle file from: /etc/kubernetes/azure.json
Traceback (most recent call last):
File "/app/./main.py", line 409, in <module>
KeyVaultAgent().grab_secrets()
File "/app/./main.py", line 300, in grab_secrets
client = self._get_client()
File "/app/./main.py", line 108, in _get_client
self._parse_sp_file()
File "/app/./main.py", line 69, in _parse_sp_file
with open(file_path, 'r') as sp_file:
PermissionError: [Errno 13] Permission denied: '/etc/kubernetes/azure.json'

**Comment by idanlevin** [comment]
https://github.com/Hexadite/acs-keyvault-agent/issues/19
