### ISSUE TITLE
Support env variables

### ISSUE THREAD

**Issue by joaocc** [Hexadite/acs-keyvault-agent#6]
Hi,
Are you planning to export secrets as env variables?
Thx

**Comment by hexadite-idan** [comment]
no such plans at the moment.
K8s secrets from Azure Key Vault is now preview in K8s 1.10, so you can use that instead and map secrets as env vars.

**Comment by nanli1022** [comment]
Hi, could you provide more details of the feature? I'm wondering how to expose the files as env variable as well. Thanks!

**Comment by serbrech** [comment]
Hi @hexadite-idan the keyvault integration in preview that I know about is to encrypt the secrets using a certificate that is stored in keyvault : https://github.com/Azure/kubernetes-kms
Is that what you are referring to? if that's the case, i don't think it is helping exporting the env variables.
If you are referring to another integration, could you please point to it?
thanks!

**Comment by idanlevin** [comment]
I switched to my personal username.

I'm not aware of any way an init-container can change another container's environment variables, if you can point me to how it's done, I might be able to add it.

**Comment by idanlevin** [comment]
@serbrech, @nanli1022 , @joaocc  can we close this issue?

**Comment by serbrech** [comment]
I suppose you can close this yes.
