### ISSUE TITLE
Export to kubernetes secrets

### ISSUE THREAD

**Issue by serbrech** [Hexadite/acs-keyvault-agent#8]
Is there a reason for not exporting the key vault secrets to kubernetes secrets?
Wondering if I’m missing something. Why was tmpfs and shared volumes prefered?

**Comment by idanlevin** [comment]
because we didn't want to keep them as k8s secrets (which are unsecured), tmpfs is temporary and the secret isn't written to disk, so it's more secure.

**Comment by idanlevin** [comment]
I'm closing this one as the ability to export as secrets was added - 
https://github.com/Hexadite/acs-keyvault-agent/pull/11
